Add better error logging and testing

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -96,6 +96,10 @@ jobs:
             echo "::error ::expected ${{ steps.test_missing_token.outcome }} to equal failure"
             exit 1
           fi
+          if [ "${{ steps.test_missing_token.outputs.error }}" != 'Token not set' ] ; then
+            echo "::error ::expected ${{ steps.test_missing_token.outputs.error }} to equal Token not set"
+            exit 1
+          fi
       - name: Invalid run group command
         id: test_invalid_run_group
         uses: ./
@@ -107,6 +111,10 @@ jobs:
         run: |
           if [ "${{ steps.test_invalid_run_group.outcome }}" != 'failure' ] ; then
             echo "::error ::expected ${{ steps.test_invalid_run_group.outcome }} to equal failure"
+            exit 1
+          fi
+          if [ "${{ steps.test_invalid_run_group.outputs.error }}" != 'run_group_id not a positive integer (nike)' ] ; then
+            echo "::error ::expected ${{ steps.test_invalid_run_group.outputs.error }} to equal run_group_id not a positive integer (nike)"
             exit 1
           fi
       - name: Invalid environment ID command
@@ -123,6 +131,10 @@ jobs:
             echo "::error ::expected ${{ steps.test_invalid_environment_id.outcome }} to equal failure"
             exit 1
           fi
+          if [ "${{ steps.test_invalid_environment_id.outputs.error }}" != 'environment_id not a positive integer (hostile)' ] ; then
+            echo "::error ::expected ${{ steps.test_invalid_environment_id.outputs.error }} to equal environment_id not a positive integer (hostile)"
+            exit 1
+          fi
       - name: Invalid conflict command
         id: test_invalid_conflict
         uses: ./
@@ -137,6 +149,10 @@ jobs:
             echo "::error ::expected ${{ steps.test_invalid_conflict.outcome }} to equal failure"
             exit 1
           fi
+          if [ "${{ steps.test_invalid_conflict.outputs.error }}" != 'WWIII not in (abort abort-all)' ] ; then
+            echo "::error ::expected ${{ steps.test_invalid_conflict.outputs.error }} to equal WWIII not in (abort abort-all)"
+            exit 1
+          fi
       - name: Invalid crowd command
         id: test_invalid_crowd
         uses: ./
@@ -149,5 +165,9 @@ jobs:
         run: |
           if [ "${{ steps.test_invalid_crowd.outcome }}" != 'failure' ] ; then
             echo "::error ::expected ${{ steps.test_invalid_crowd.outcome }} to equal failure"
+            exit 1
+          fi
+          if [ "${{ steps.test_invalid_crowd.outputs.error }}" != 'hipsters not in (default automation automation_and_crowd on_premise_crowd)' ] ; then
+            echo "::error ::expected ${{ steps.test_invalid_crowd.outputs.error }} to equal hipsters not in (default automation automation_and_crowd on_premise_crowd)"
             exit 1
           fi
diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -52,6 +52,9 @@ outputs:
   command:
     description: The CLI command that was run
     value: ${{ steps.validate.outputs.command }}
+  error:
+    description: The validation error that was raised
+    value: ${{ steps.validate.outputs.error }}
 
 runs:
   using: composite
@@ -72,16 +75,21 @@ runs:
 
         echo "::add-mask::${{ inputs.token }}"
 
+        # Define error helper
+        error () {
+          echo "::error ::${1}"
+          echo "::set-output name=error::${1}"
+          exit 1
+        }
+
         # Validate token
         if [ -z "${{ inputs.token }}" ] ; then
-          echo "Error: Token not set"
-          exit 1
+          error "Token not set"
         fi
 
         # Validate run_group_id
         if ! echo "${{ inputs.run_group_id }}" | grep -Eq '^[0-9]+$' ; then
-          echo "Error: run_group_id not a positive integer (${{ inputs.run_group_id }})"
-          exit 1
+          error "run_group_id not a positive integer (${{ inputs.run_group_id }})"
         fi
 
         RUN_COMMAND="run --skip-update --token ${{ inputs.token }} --run-group ${{ inputs.run_group_id }} --junit-file results/rainforest/junit.xml"
@@ -94,8 +102,7 @@ runs:
               RUN_COMMAND="${RUN_COMMAND} --conflict ${{ inputs.conflict }}"
             ;;
             *)
-              echo "Error: ${1} not in (abort abort-all)"
-              exit 1
+              error "${{ inputs.conflict }} not in (abort abort-all)"
             ;;
           esac
         fi
@@ -110,8 +117,7 @@ runs:
           if echo "${{ inputs.environment_id }}" | grep -Eq '^[0-9]+$' ; then
             RUN_COMMAND="${RUN_COMMAND} --environment-id ${{ inputs.environment_id }}"
           else
-            echo "Error: environment_id not a positive integer (${{ inputs.environment_id }})"
-            exit 1
+            error "environment_id not a positive integer (${{ inputs.environment_id }})"
           fi
         fi
 
@@ -125,8 +131,7 @@ runs:
                 RUN_COMMAND="${RUN_COMMAND} --crowd ${{ inputs.crowd }}"
             ;;
             *)
-              echo "Error: ${{ inputs.crowd }} not in (default automation automation_and_crowd on_premise_crowd)"
-              exit 1
+              error "${{ inputs.crowd }} not in (default automation automation_and_crowd on_premise_crowd)"
             ;;
           esac
         fi
